### ISSUE TITLE
Update Manager Bug

### ISSUE THREAD

**Issue by rbeltz48** [linuxmint/lmde-5-cinnamon-beta#17]
Update Manager keeps popping up on the desktop. This has never happened before with any previous releases of LMDE or regular Mint edition. Using MATE desktop. It is distracting and annoying. Please fix. Thanks.

**Comment by mtwebster** [comment]
Can you be more detailed about what's happening?

The update manager window keeps becoming visible? Then you close it, and it appears again? Does it come back during the same session? Or after a reboot?

Have you clicked 'ok' on the initial welcome page for it? Until you do, the window *will* keep reappearing after login.

**Comment by rbeltz48** [comment]
Michael, 

Update Manager stopped popping up after I clicked on it after installation. But I don't remember this happening before with any earlier version of Mint (back to Mint 13) or LMDE 2,3 or 4. Must be something new??

**Comment by mtwebster** [comment]
It was introduced here: https://github.com/linuxmint/mintupdate/commit/82453c34788e25a6781133988966200f9c13042d

I believe it was first in Mint 20.2. It's in LMDE4 since around then also, but as you would have gotten it there in the form of an update, the welcome page may have already been dismissed, so you never encountered it.
