### ISSUE TITLE
Thunderbird 24.4.0 Not Working

### ISSUE THREAD

**Issue by rbeltz48** [linuxmint/lmde-5-cinnamon-beta#18]
I have used this version of Thunderbird for many years in many different Debian distros. It works perfectly on LMDE4, MX Linux 18, 19, and 21, Sparky 7 and Debian 11. It freezes and doesn't work properly on LMDE5. Please investigate. Thanks.

**Comment by xenopeek** [comment]
Please add more detailed information.

1. When does it freeze? Immediately after you start it from the menu, when you perform some specific action, or …?
1. Did it freeze on first run or did it start at some later point? For example did it start after you added accounts, imported a mailbox backup, installed add-ons, or …?
1. When happens when it freezes? Is the window still displayed correctly but no longer accepts input? Can you still move the window around? Is the mouse cursor (when over the window) a normal pointer or is it the animated loading cursor?
1. Try starting Thunderbird in safe mode. For this open the terminal and run the command `thunderbird --safe-mode`. Does that make a difference for the freezing?

**Comment by mtwebster** [comment]
It seems to run well enough for me with a gmail account. It did crash a few times when I attempted to navigate around while it was doing its initial sync (of 20k+ emails), but after allowing it to complete, it seems stable and responsive enough.

**Comment by rbeltz48** [comment]
To both developers on this issue. The main Email screen comes up. If you click on Inbox it either does nothing or the application crashes and it doesn't even show the total number of Emails in the Inbox. Clicking on other Email boxes does the same thing, either crashing or freezing. It does the same thing in safe mode.

I upgraded to Ver. 78.14.0 and it seems to run OK. Again Ver. 24.4.0 never did any of this before with any distro. Thanks.

**Comment by rbeltz48** [comment]
Closing it since Ver. 78.14.0 works OK.
