### ISSUE TITLE
Cyberhost VPN

### ISSUE THREAD

**Issue by exit885** [linuxmint/lmde-5-cinnamon-beta#45]
I have created a Cyberhost VPN on LMDE 4 and it works perfectly. 
On LMDE 5 it is not possible to get the Cyberhost VPN to work.
I keep getting the message: 
The VPNconnection "openvpn" failed because the VPN service returned invalid configuration.

**Comment by mtwebster** [comment]
What happens if you run `cyberghostvpn connect`?

What version are you running? The latest from their site says unsupported during installation (ubuntu derivatives only). I modified the script to make it install, but it doesn't work - I don't get anything referring to openvpn, however.. just authentication failing (it can't even make a connection). This is a vm, I'll try a real machine also.

**Comment by mtwebster** [comment]
Closing this, as I have a feeling it's something they would have to fix or address.  I'll still get notifications if you can provide more info.  Thanks
